global:
  scrape_interval: 15s
  evaluation_interval: 15s

# ========== ALERTING ==========
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# ========== ALERT RULES ==========
rule_files:
  - "alert_rules.yml"

scrape_configs:

  # ========== PROMETHEUS ==========
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # ========== SNMP UBIQUITI ==========
  - job_name: 'snmp-ubiquiti'
    metrics_path: /snmp

    params:
      module: [ubiquiti]
      auth: [public_v2]

    static_configs:
      - targets:
          - 10.100.0.3
          - 10.100.1.3

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target

      - source_labels: [__param_target]
        target_label: instance

      - target_label: __address__
        replacement: snmp_exporter:9116

  # ========== NODE EXPORTER ==========
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
