# Section globale : paramètres par défaut pour Prometheus
global:
  # Intervalle par défaut entre deux scrapes (interrogations des cibles)
  scrape_interval: 5s   # Prometheus va collecter les métriques toutes les 5 secondes

# Liste des jobs à scrapper (cibles à surveiller)
scrape_configs:
  - job_name: 'prometheus'   # Nom du job : ici on surveille Prometheus lui-même

    # Configuration des cibles statiques pour ce job
    static_configs:
      - targets: ['prometheus:9090']  # Liste des cibles à interroger
                                       # Ici, 'prometheus' = nom du container Docker
                                       # 9090 = port où Prometheus expose ses métriques

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']


  - job_name: 'snmp_if_mib'          # Job pour superviser les périphériques réseau via SNMP
    static_configs:
      - targets:
          - "10.10.27.105:161"    # IP du switch / routeur / PC que tu veux surveiller
    metrics_path: /snmp        # Chemin où Prometheus va interroger l'exporter SNMP
    params:
      module: [if_mib]        # Indique à l'exporter SNMP quel module utiliser (ici "default" du snmp.yml)
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
        # Transforme l'adresse de la cible en paramètre 'target' pour SNMP exporter
      - source_labels: [__param_target]
        target_label: instance
        # Définit le label 'instance' avec l'adresse de la cible (utile pour identifier la source dans Grafana)
      - target_label: __address__
        replacement: snmp_exporter:9116
        # Remplace l'adresse de scrape par l'adresse de l'exporter SNMP
        # Prometheus interrogera donc snmp_exporter:9116 et pas directement l'équipement
